# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sp < Formula
  desc "A daily scratchpad for quick notes and todos"
  homepage "https://github.com/pders01/sp"
  version "0.7.4"

  on_macos do
    on_intel do
      url "https://github.com/pders01/sp/releases/download/v0.7.4/sp_Darwin_x86_64.tar.gz"
      sha256 "5f7ca3ca2bdce2988f03203d92a88f9a50e5a908da600181b2ecfca356000c11"

      def install
        bin.install "sp"
      end
    end
    on_arm do
      url "https://github.com/pders01/sp/releases/download/v0.7.4/sp_Darwin_arm64.tar.gz"
      sha256 "a43b38f279a7d102138174b9736d7c649fb59d4de9c2dd43003cc504b81ff505"

      def install
        bin.install "sp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pders01/sp/releases/download/v0.7.4/sp_Linux_x86_64.tar.gz"
        sha256 "3510bc4d6129fbbda5e44c3289d517edde02b0195514daccf9ef12c3507b545d"

        def install
          bin.install "sp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pders01/sp/releases/download/v0.7.4/sp_Linux_arm64.tar.gz"
        sha256 "581914cad62cab86e7d185338c67446ab861f4123fa7908a30936ad8a7cbadab"

        def install
          bin.install "sp"
        end
      end
    end
  end
end
